<?php

/**
 * @file
 * Contains module hooks.
 */

/**
 * Implements hook_theme().
 */
function hm_newsletter_theme($existing, $type, $theme, $path) {
  return array(
    'hm_newsletter_form' => array(
      'variables' => array(
        'newsletters' => NULL,
        'client_id' => '',
        'birthday' => array(),
        'imprint_text' => '',
        'title' => 1,
        'firstname' => 1,
        'name' => 1,
        'zipcode' => 1,
        'location' => 1,
        'birthdate' => 1,
        'headline' => '',
        'text' => '',
        'confirmation_headline' => '',
        'confirmation_text' => '',
      ),
    ),
  );
}
